package nl.toolforge.karma.core.cmd;

/**
 * A command message is a message container for messages generated by <code>Command</code>s. A general message from a
 * <code>CVS</code>-command could be an <code>OK</code> from the server. Another example is a message containing a
 * formatted string
 *
 *
 * @author D.A. Smedes
 *
 * @version $Id$
 */
public interface CommandMessage {

  /**
	 * Returns the message with id <code>index</code> in a human readable form. This string should be formatted without
	 * newline characters, to enable any interface application to process them easily.
	 *
	 * @param index The index of the message.
	 *
	 * @return
	 */
	public String getMessageText(int index);
}
