package nl.toolforge.karma.core.cmd;

/**
 * <p>A command message is a message container for messages generated by <code>Command</code>s. A general message from a
 * <code>CVS</code>-command could be an <code>OK</code> from the server. Another example is a message containing a
 * formatted string.
 *
 * @author D.A. Smedes
 * @version $Id$
 */
public interface CommandMessage {

	/**
	 * Returns the message in a human readable form. This string should be formatted without
	 * newline characters, to enable any interface application to process them easily.
	 *
	 * @return The message text of this message.
	 */
	public String getMessageText();
}
